name: activity type test

on:
  issues:
    types: [ opened, edited, closed ]

jobs:
  create-issue-on-failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: workflow-call
        uses: ./.github/workflows/dispatch_test.yml
        with:
          title: "Automated workflow failure issue for commit ${{ github.sha }}"
          body: "This issue was automatically created by the GitHub Action workflow ** ${{ github.workflow }} **"
