name: Cache

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache test
        uses: actions/cache@v3
        env:
          cache-name: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ matrix.os }}-Cache-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-Cache-${{ env.cache-name }}-${{ runner.os }}-Cache-${{ runner.os }}-
