name: Create Issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    outputs:
      issue-num: ${{ steps.create-issue.outputs.issue-number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Issue
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Failure: ${{ inputs.title }}",
            "body": "Details: ${{ inputs.body }}"
            }' \
          --fail
