name: Create Issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        id: create_issue
        uses: actions/github-script@v6
        with:
          script: |
            const title = '${{ inputs.title }}';
            const body = '${{ inputs.body }}';
            const response = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
            });
            return response.data.number;

      - name: Output issue number
        id: output_issue_number
        run: echo "issue-num=${{ steps.create_issue.outputs.result }}" >> $GITHUB_ENV
