name: IO_4

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changelog:
        description: "The generated changelog for the new version"
      clean_changelog:
        description: "The generated changelog for the new version without the version name in it"
      version:
        description: "The new version"
    env:
      ARTIFACT_TAG: ${{ steps.changelog.outputs.version }}
    
    steps:
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.0
        runs: |
          echo "Build Success $ARTIFACT_TAG"
        
