name: IO_4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-tag: ${{ steps.changelog.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0

      - name: Display Changelog
        run: cat CHANGELOG.md

      - name: Print Changelog Version
        run: echo "Build Success! Version: ${{ steps.changelog.outputs.version }}"
