name: IO_4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display package.json
        run: cat package.json

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0
        with:
          # Ensure that the `package.json` is used for version detection
          version-file: './package.json'
          version-path: 'version'

      - name: Print Changelog Version
        run: echo "Build Success! Version: ${{ steps.changelog.outputs.version }}"
