name: IO_4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.3.0

  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        env:
          TAG: ${{ steps.changelog.outputs.version }}
        run: echo "Build Success! $TAG"
