name: Matrix_create_issue

on:
  push:

jobs:
  create-new-issue:
    strategy:
      matrix:
        prod: [prod1, prod2]
        level: [dev, stage, prod]
    uses: ./.github/workflows/create-issue.yml
    with:
      title: "${{ matrix.prod }} issue"
      body: "Update for ${{ matrix.level }}"
      continue-on-error: true # 조합 하나가 실패해도 워크플로는 나머지 행렬 처리 계속함
    secrets: inherit
    permissions:
      issues: write

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: echo ${{ needs.create-new-issue.outputs.issue-num }}
