name: Create demo issue 3

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest,window-latest]
        node-version: [14,16]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
