name: Verify file

on:
  push:
  pull_request:
  
  permissions:
    issues: write

jobs:
  verify:
    name: ${{ vars.JOBS_NAME }}
    if: ${{ vars.EXEC_WF == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: | 
          [[ -f ${{ vars.FILE_TO_CHECK }} ]] || ( echo "${{ vars.FILE_TO_CHECK }} file needs to be added to ${{ github.repository }} !" )
      # ${{ github.repository }} !" 뒤에 && exit 1를 넣으면 종료상태를 1로 설정하여 오류를 발생시킬 수 있음
